CREATE DATABASE QL_NhaHang
GO
USE QL_NhaHang
GO

CREATE TABLE BAN
(
	ID int IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100)NOT NULL DEFAULT N'Chưa có tên',
	STATUS NVARCHAR(100)NOT NULL DEFAULT N'Trống',
)

CREATE TABLE TAIKHOAN
(
	TENTK NVARCHAR(100) PRIMARY KEY,
	TENHT NVARCHAR(100) NOT NULL DEFAULT N'Hin',
	PASSWORD NVARCHAR(1000) NOT NULL DEFAULT 0,
	TYPE INT NOT NULL DEFAULT 0
)

CREATE TABLE DANHMUC
(
	ID int IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100) NOT NULL
)

CREATE TABLE MONAN
(
	ID int IDENTITY PRIMARY KEY,
	NAME NVARCHAR(100)NOT NULL DEFAULT N'Chưa có tên',
	IDDM INT NOT NULL,
	GIA FLOAT NOT NULL DEFAULT 0
	FOREIGN KEY (IDDM) REFERENCES DBO.DANHMUC(ID)
)

CREATE TABLE HOADON
(
	ID int IDENTITY PRIMARY KEY,
	NGAYNHAN DATE NOT NULL DEFAULT GETDATE(),
	NGAYTRA DATE ,
	IDBAN INT NOT NULL,
	STATUS INT NOT NULL DEFAULT 0,
	DISCOUNT INT,
	TONGTIEN FLOAT
	FOREIGN KEY (IDBAN) REFERENCES DBO.BAN(ID)
)
UPDATE DBO.HOADON SET DISCOUNT = 0


CREATE TABLE CHITIETHOADON
(
	ID int IDENTITY PRIMARY KEY,
	IDHOADON INT NOT NULL,
	IDMONAN INT NOT NULL,
	COUNT INT NOT NULL DEFAULT 0
	FOREIGN KEY (IDHOADON) REFERENCES DBO.HOADON(ID),
	FOREIGN KEY (IDMONAN) REFERENCES DBO.MONAN(ID)
)


INSERT INTO DBO.TAIKHOAN(TENTK,TENHT ,PASSWORD,TYPE)
VALUES(N'GV',N'GIAVI',N'1',1)

INSERT INTO DBO.TAIKHOAN(TENTK,TENHT ,PASSWORD,TYPE)
VALUES(N'U',N'USER',N'1',0)



GO
CREATE PROC USP_LayTaiKhoanTenTK
@TENTK NVARCHAR(100)
AS
BEGIN
	SELECT * FROM DBO.TAIKHOAN WHERE @TENTK = TENTK
END
GO

EXEC DBO.USP_LayTaiKhoanTenTK @TENTK = N'GV'

--SELECT COUNT(*) FROM DBO.TAIKHOAN WHERE TENTK = N'GV' AND PASSWORD = N'2'
GO
CREATE PROC USP_Login
@TENTK NVARCHAR(100),@PASSWORD NVARCHAR(1000)
AS 
BEGIN
	SELECT * FROM DBO.TAIKHOAN WHERE TENTK = @TENTK AND PASSWORD=@PASSWORD
END
GO
EXEC DBO.USP_Login @TENTK = N'GV', @PASSWORD = '1'


DECLARE @I INT = 0
WHILE @i <= 10
BEGIN
	INSERT DBO.BAN(name) VALUES ( N'Bàn' + CAST (@i AS nvarchar(100)))
	SET @i = @i + 1
END
SELECT *FROM DBO.BAN

GO
CREATE PROC USP_LayDSBan
AS SELECT *FROM DBO.BAN
GO

UPDATE DBO.BAN SET STATUS = N'Có người' WHERE id = 9

EXEC DBO.USP_LayDSBan

---DANH MUC MÓN ?N
INSERT DBO.DANHMUC (NAME)
VALUES(N'Hải Sản')
INSERT DBO.DANHMUC (NAME)
VALUES(N'Nông Sản')
INSERT DBO.DANHMUC (NAME)
VALUES(N'Lẩu')
INSERT DBO.DANHMUC (NAME)
VALUES(N'Nước')
---CÁC MÓN ?N
INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Mực Hấp',1,200000)
INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Cua Hấp',1,300000)
INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Cá SaPa Nướng',1,150000)

INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Thịt Heo Nướng',2,200000)
INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Thịt Bò Tái',2,300000)
INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Gà Nướng',2,150000)

INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Lẩu Bò',3,300000)
INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Lẩu Dê',3,250000)
INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Lẩu Cá Hú',3,100000)

INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Nước Ngọt',4,20000)
INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Nước Suối',4,15000)
INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'Bia',4,30000)

---HOÁ ??N
INSERT DBO.HOADON(NGAYNHAN,NGAYTRA,IDBAN,STATUS)
VALUES(GETDATE(),NULL,1,0)
INSERT DBO.HOADON(NGAYNHAN,NGAYTRA,IDBAN,STATUS)
VALUES(GETDATE(),NULL,2,0)
INSERT DBO.HOADON(NGAYNHAN,NGAYTRA,IDBAN,STATUS)
VALUES(GETDATE(),GETDATE(),2,1)

---CHI TI?T HOÁ ??N
INSERT DBO.CHITIETHOADON(IDHOADON,IDMONAN,COUNT)
VALUES(1,1,2)
INSERT DBO.CHITIETHOADON(IDHOADON,IDMONAN,COUNT)
VALUES(1,3,4)
INSERT DBO.CHITIETHOADON(IDHOADON,IDMONAN,COUNT)
VALUES(1,5,1)

INSERT DBO.CHITIETHOADON(IDHOADON,IDMONAN,COUNT)
VALUES(22,1,2)
INSERT DBO.CHITIETHOADON(IDHOADON,IDMONAN,COUNT)
VALUES(23,6,2)
INSERT DBO.CHITIETHOADON(IDHOADON,IDMONAN,COUNT)
VALUES(24,5,2)

SELECT * FROM DBO.HOADON WHERE IDBAN = 2 AND STATUS = 1

SELECT MA.NAME,CTHD.COUNT,MA.GIA,MA.GIA*CTHD.COUNT AS TongTien FROM DBO.CHITIETHOADON AS CTHD,DBO.HOADON AS HD,DBO.MONAN AS MA
WHERE CTHD.IDHOADON = HD.ID AND CTHD.IDMONAN = MA.ID AND HD.STATUS = 0 AND HD.IDBAN = 2


GO
CREATE PROC USP_InsertHoaDon
@IDBAN INT
AS
BEGIN
	INSERT DBO.HOADON(NGAYNHAN,NGAYTRA,IDBAN,STATUS,DISCOUNT)
	VALUES(GETDATE(),NULL,@IDBAN,0,0)
END
GO
CREATE PROC USP_InsertChiTietHoaDon
@IDHOADON INT, @IDMONAN INT , @COUNT INT
AS
BEGIN
	DECLARE @isExitsChiTietHoaDon INT;
	DECLARE @foodCount INT = 1;
	SELECT @isExitsChiTietHoaDon = id, @foodCount = CTHD.COUNT 
	FROM DBO.CHITIETHOADON AS CTHD 
	WHERE IDHOADON = @IDHOADON AND IDMONAN  = @IDMONAN
	IF(@isExitsChiTietHoaDon >0)
	BEGIN 
		DECLARE @newCount INT = @foodCount + @count
		IF(@newCount > 0)
			UPDATE DBO.CHITIETHOADON SET count = @foodCount + @count WHERE IDMONAN = @IDMONAN
		ELSE
			DELETE DBO.CHITIETHOADON WHERE IDHOADON = @IDHOADON AND IDMONAN = @IDMONAN
	END
	ELSE
	BEGIN
	INSERT DBO.CHITIETHOADON(IDHOADON,IDMONAN,COUNT)
	VALUES(@IDHOADON,@IDMONAN,@COUNT)
END
END
GO
SELECT MAX(id) FROM DBO.HOADON

UPDATE DBO.HOADON SET STATUS = 1 WHERE id = 1
GO

DELETE DBO.CHITIETHOADON
DELETE DBO.HOADON


GO
CREATE TRIGGER UTG_UpdateChiTietHoaDon
ON DBO.CHITIETHOADON 
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @IDHOADON INT
	DECLARE @IDBAN INT

    SELECT @IDHOADON = IDHOADON FROM inserted

    SELECT @IDBAN = IDBAN FROM DBO.HOADON WHERE id = @IDHOADON AND STATUS = 0

	DECLARE @COUNT INT 
	SELECT @COUNT = COUNT(*) FROM DBO.CHITIETHOADON WHERE IDHOADON = @IDHOADON
	IF(@COUNT > 0)
	BEGIN
		PRINT @IDBAN
		PRINT @IDHOADON
		PRINT @COUNT
		UPDATE DBO.BAN SET STATUS = N'Có Người' WHERE id = @IDBAN
	END
	ELSE
	BEGIN
		PRINT @IDBAN
		PRINT @IDHOADON
		PRINT @COUNT
		UPDATE DBO.BAN SET STATUS = N'Trống' WHERE id = @IDBAN
	END
END
GO


CREATE TRIGGER UTG_UpdateHoaDon
ON DBO.HOADON FOR UPDATE 
AS
BEGIN
	DECLARE @IDHOADON INT
	DECLARE @IDBAN INT

	SELECT @IDHOADON = ID FROM inserted

	SELECT @IDBAN = IDBAN FROM DBO.HOADON WHERE ID = @IDHOADON

	DECLARE @COUNT INT = 0 
	SELECT @COUNT = COUNT(*) FROM DBO.HOADON WHERE IDBAN = @IDBAN AND STATUS = 0

	IF(@COUNT = 0)
	BEGIN
		UPDATE DBO.BAN SET STATUS = N'Trống' WHERE ID = @IDBAN
	END
END

--13
GO
CREATE PROC USP_SwitchTable
@IDBAN1 INT, @IDBAN2 INT
AS 
BEGIN
	DECLARE @IDHoaDonDau INT
	DECLARE @IDHOADONHAI INT

	DECLARE @isFirstTablEmpty INT =1
	DECLARE @isSecondTablEmpty INT =1


	SELECT @IDHOADONHAI = id FROM DBO.HOADON  WHERE IDBAN = @IDBAN2 AND STATUS = 0
	SELECT @IDHOADONDAU = id FROM DBO.HOADON  WHERE IDBAN = @IDBAN1 AND STATUS = 0

	PRINT @IDHOADONDAU
	PRINT @IDHOADONHAI

	IF(@IDHoaDonDau IS NULL)
	BEGIN
		INSERT DBO.HOADON(NGAYNHAN,NGAYTRA,IDBAN,STATUS)
		VALUES(GETDATE(),NULL,@IDBAN1,0)
		SELECT @IDHoaDonDau = MAX(id) fROM DBO.HOADON WHERE IDBAN = @IDBAN1 AND STATUS = 0
	END
	SELECT @isFirstTablEmpty = COUNT(*) FROM DBO.CHITIETHOADON WHERE IDHOADON = @IDHoaDonDau
	IF(@IDHOADONHAI IS NULL)
	BEGIN
		INSERT DBO.HOADON(NGAYNHAN,NGAYTRA,IDBAN,STATUS)
		VALUES(GETDATE(),NULL,@IDBAN2,0)
		SELECT @IDHOADONHAI = MAX(id) fROM DBO.HOADON WHERE IDBAN = @IDBAN2 AND STATUS = 0
	END
	SELECT @isSecondTablEmpty = COUNT(*) FROM DBO.CHITIETHOADON WHERE IDHOADON = @IDHOADONHAI
	SELECT id INTO IDBillInfoTable
	FROM DBO.CHITIETHOADON
	WHERE IDHOADON = @IDHOADONHAI

	UPDATE DBO.CHITIETHOADON SET IDHOADON = @IDHOADONHAI WHERE IDHOADON = @IDHoaDonDau

	UPDATE DBO.CHITIETHOADON SET IDHOADON = @IDHoaDonDau WHERE  id IN (SELECT * FROM IDBillInfoTable)

	DROP TABLE IDBillInfoTable
	IF(@isFirstTablEmpty = 0)
		UPDATE DBO.BAN SET STATUS = N'Trống' WHERE id = @IDBAN2
	IF(@isSecondTablEmpty = 0)
		UPDATE DBO.BAN SET STATUS = N'Trống' WHERE id = @IDBAN1
END
GO

UPDATE DBO.BAN SET STATUS = N'Trống'

GO
CREATE PROC USP_GetListBillByDate
@NGAYNHAN DATE,@NGAYTRA DATE
AS
BEGIN
		SELECT B.NAME AS [Tên Bàn], HD.TONGTIEN AS [Tổng Tiền], HD.NGAYNHAN AS [Ngày Vào], HD.NGAYTRA AS [Ngày Ra], HD.DISCOUNT AS [Giảm Giá] 
		FROM DBO.HOADON AS HD
		INNER JOIN DBO.BAN AS B ON B.ID = HD.IDBAN
		WHERE HD.NGAYNHAN >= @NGAYNHAN 
			AND HD.NGAYTRA <= @NGAYTRA 
			AND HD.STATUS = 1
END

GO
CREATE PROC USP_UpdateAccount
@TENTK NVARCHAR(100), @TENHT NVARCHAR(100), @PASSWORD NVARCHAR(100), @NEWPASSWORD NVARCHAR(100)
AS
BEGIN
	DECLARE @isRightPass INT = 0

	SELECT @isRightPass = COUNT(*) FROM DBO.TAIKHOAN WHERE TENHT = @TENHT AND PASSWORD = @PASSWORD

	IF(@isRightPass = 1)
	BEGIN
		IF(@NEWPASSWORD = NULL OR @NEWPASSWORD = '')
		BEGIN
			UPDATE DBO.TAIKHOAN SET TENHT = @TENHT WHERE TENTK = @TENTK
		END
		ELSE
			UPDATE DBO.TAIKHOAN SET TENHT = @TENHT, PASSWORD = @NEWPASSWORD WHERE TENTK = @TENTK
END		
END

INSERT DBO.MONAN (NAME,IDDM,GIA)
VALUES(N'',0,0.0)

UPDATE DBO.MONAN SET NAME = N'', IDDM = 5 , GIA = 0 WHERE id = 4 

GO
CREATE TRIGGER UTG_DeleteBillInfo
ON DBO.CHITIETHOADON FOR DELETE
AS
BEGIN
	DECLARE @IDCTHD INT 
	DECLARE @IDHOADON INT
	SELECT @IDCTHD = id, @IDHOADON = deleted.IDHOADON FROM deleted

	DECLARE @IDBAN INT
	SELECT @IDBAN = IDBAN FROM DBO.HOADON WHERE id = @IDHOADON

	DECLARE @COUNT INT = 0
	SELECT @COUNT = COUNT(*) FROM DBO.CHITIETHOADON AS CTHD, DBO.HOADON AS HD WHERE HD.id = CTHD.IDHOADON AND HD.ID = @IDHOADON AND HD.STATUS = 0

	IF(@COUNT = 0)
		UPDATE DBO.BAN SET STATUS = N'Trống' WHERE id = @IDBAN
END

--Chuy?n Ký T? //// vidu CRATE FUNCTION 

SELECT TENTK,TENHT,TYPE FROM DBO.TAIKHOAN

GO
--phan trang
CREATE PROC USP_GetListBillByDateAndPage
@NGAYNHAN DATE,@NGAYTRA DATE,@PAGE INT
AS
BEGIN
		DECLARE @PAGEROWS INT = 10
		DECLARE @SELECTROWS INT = @PAGEROWS
		DECLARE @EXCEPTROWS INT = (@PAGE -1) * @PAGEROWS
		;WITH BillShow AS (SELECT HD.ID, B.NAME AS [Tên Bàn], HD.TONGTIEN AS [Tổng Tiền], HD.NGAYNHAN AS [Ngày Vào], HD.NGAYTRA AS [Ngày Ra], HD.DISCOUNT AS [Giảm Giá] 
		FROM DBO.HOADON AS HD
		INNER JOIN DBO.BAN AS B ON B.ID = HD.IDBAN
		WHERE HD.NGAYNHAN >= @NGAYNHAN 
			AND HD.NGAYTRA <= @NGAYTRA 
			AND HD.STATUS = 1)

		SELECT TOP (@SELECTROWS) * FROM BillShow WHERE id NOT IN (SELECT TOP (@EXCEPTROWS) id FROM BillShow)

END

GO
CREATE PROC USP_GetNumBillByDate
@NGAYNHAN DATE,@NGAYTRA DATE
AS
BEGIN
		SELECT COUNT(*)
		FROM DBO.HOADON AS HD
		INNER JOIN DBO.BAN AS B ON B.ID = HD.IDBAN
		WHERE HD.NGAYNHAN >= @NGAYNHAN 
			AND HD.NGAYTRA <= @NGAYTRA 
			AND HD.STATUS = 1
END



SELECT * FROM DBO.TAIKHOAN
SELECT *FROM HOADON
SELECT *FROM DANHMUC
SELECT *FROM MONAN
SELECT *FROM CHITIETHOADON